### ISSUE TITLE
unbox failed

### ISSUE THREAD

**Issue by tansaku** [Paperchain/nuxt-box#5]
**Describe the bug**

```
❯ truffle unbox Paperchain/nuxt-box
Starting unbox...
=================
✔ Preparing to download box
✔ Downloading
npm ERR! code 128
npm ERR! git dep preparation failed
npm ERR! command /Users/samueljoseph/.nvm/versions/node/v16.3.0/bin/node /Users/samueljoseph/.nvm/versions/node/v16.3.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/samueljoseph/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 128
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command git --no-replace-objects clone --mirror -q ssh://git@github.com/gulpjs/gulp.git /Users/samueljoseph/.npm/_cacache/tmp/git-clone-c684df77/.git
npm ERR! npm ERR! fatal: destination path '/Users/samueljoseph/.npm/_cacache/tmp/git-clone-c684df77/.git' already exists and is not an empty directory.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/samueljoseph/.npm/_logs/2021-07-06T09_59_42_190Z-debug.log
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/samueljoseph/.npm/_logs/2021-07-06T09_59_44_684Z-debug.log
✔ Cleaning up temporary files
✖ Setting up box
Unbox failed!
✖ Setting up box
Unbox failed!
Error: Command failed: npm install
npm ERR! code 128
npm ERR! git dep preparation failed
npm ERR! command /Users/samueljoseph/.nvm/versions/node/v16.3.0/bin/node /Users/samueljoseph/.nvm/versions/node/v16.3.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/samueljoseph/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 128
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command git --no-replace-objects clone --mirror -q ssh://git@github.com/gulpjs/gulp.git /Users/samueljoseph/.npm/_cacache/tmp/git-clone-c684df77/.git
npm ERR! npm ERR! fatal: destination path '/Users/samueljoseph/.npm/_cacache/tmp/git-clone-c684df77/.git' already exists and is not an empty directory.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/samueljoseph/.npm/_logs/2021-07-06T09_59_42_190Z-debug.log
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/samueljoseph/.npm/_logs/2021-07-06T09_59_44_684Z-debug.log
    at checkExecSyncError (node:child_process:707:11)
    at Object.execSync (node:child_process:744:15)
    at Object.installBoxDependencies (/Users/samueljoseph/.nvm/versions/node/v16.3.0/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:136:1)
    at Object.setUpBox (/Users/samueljoseph/.nvm/versions/node/v16.3.0/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:66:1)
    at /Users/samueljoseph/.nvm/versions/node/v16.3.0/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:116:1
    at Generator.next (<anonymous>)
    at fulfilled (/Users/samueljoseph/.nvm/versions/node/v16.3.0/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:42)

```

maybe I need to be on an earlier version of node?  I'm on OSX 11.4, node 16.3.0 ...

**Comment by tansaku** [comment]
I backed out to node 14.7 but different set of errors:

```
In file included from ../src/node-boilerplate/scrypt_common.cc:28:
In file included from ../../nan/nan.h:2657:
../../nan/nan_object_wrap.h:24:25: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object>'
    assert(persistent().IsNearDeath());
           ~~~~~~~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../src/node-boilerplate/scrypt_common.cc:28:
In file included from ../../nan/nan.h:2657:
../../nan/nan_object_wrap.h:67:18: error: no member named 'MarkIndependent' in 'Nan::Persistent<v8::Object>'
    persistent().MarkIndependent();
    ~~~~~~~~~~~~ ^
../../nan/nan_object_wrap.h:124:26: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object>'
    assert(wrap->handle_.IsNearDeath());
           ~~~~~~~~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../src/node-boilerplate/scrypt_common.cc:28:
In file included from ../../nan/nan.h:2753:
../../nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See http://crbug.com/v8/9908. [-Wdeprecated-declarations]
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                          ^
/Users/samueljoseph/Library/Caches/node-gyp/14.17.0/include/node/v8.h:5272:3: note: 'GetContents' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use GetBackingStore. See http://crbug.com/v8/9908.")
  ^
/Users/samueljoseph/Library/Caches/node-gyp/14.17.0/include/node/v8config.h:402:39: note: expanded from macro 'V8_DEPRECATE_SOON'
# define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
                                      ^
../src/node-boilerplate/scrypt_common.cc:98:12: warning: address of stack memory associated with local variable 'scrypt_err_description' returned [-Wreturn-stack-address]
    return scrypt_err_description.c_str();
           ^~~~~~~~~~~~~~~~~~~~~~
2 warnings and 15 errors generated.
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/samueljoseph/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command "/Users/samueljoseph/.nvm/versions/node/v14.17.0/bin/node" "/Users/samueljoseph/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/samueljoseph/Documents/Github/neurogrid/test/node_modules/scrypt
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/samueljoseph/.npm/_logs/2021-07-12T11_40_19_177Z-debug.log

    at checkExecSyncError (child_process.js:640:11)
    at Object.execSync (child_process.js:676:15)
    at Object.installBoxDependencies (/Users/samueljoseph/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:139:1)
    at Object.setUpBox (/Users/samueljoseph/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:66:1)
    at /Users/samueljoseph/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:183:1
    at Generator.next (<anonymous>)
    at fulfilled (/Users/samueljoseph/.nvm/versions/node/v14.17.0/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:42)
Truffle v5.4.0 (core: 5.4.0)
Node v14.17.0
```

**Comment by tansaku** [comment]
in both cases I did get a small truffle project created

**Comment by BenAzlay** [comment]
I use Node v14.15.4 and I have this set of errors:
```gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\benja\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\benja\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\benja\OneDrive\Documents\Projects\nuxt-box-test\node_modules\scrypt
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\benja\AppData\Roaming\npm-cache\_logs\2021-08-11T20_08_25_179Z-debug.log
√ Cleaning up temporary files
× Setting up box
Unbox failed!
× Setting up box
Unbox failed!
Error: Command failed: npm install
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\benja\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\benja\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\benja\OneDrive\Documents\Projects\nuxt-box-test\node_modules\scrypt
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\benja\AppData\Roaming\npm-cache\_logs\2021-08-11T20_08_25_179Z-debug.log

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.installBoxDependencies (C:\Users\benja\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\lib\utils\unbox.js:139:1)
)
    at C:\Users\benja\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\box.js:183:1
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\benja\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\box.js:5:42)
Truffle v5.4.5 (core: 5.4.5)
Node v14.15.4```

**Comment by Thomas-Philippot** [comment]
Had similar issue, managed to install with node 11
